# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10qNzAKnM9I3yiMWyjx09DgKurHJlPOff
"""

import sqlite3
import urllib.request

# Create/connect to database
conn = sqlite3.connect('emaildb.sqlite')
cur = conn.cursor()

# Drop and create the Counts table
cur.execute('DROP TABLE IF EXISTS Counts')
cur.execute('CREATE TABLE Counts (org TEXT, count INTEGER)')

# Download the data file
url = 'https://www.py4e.com/code3/mbox.txt'
fname = 'mbox.txt'
urllib.request.urlretrieve(url, fname)

# Open and process the file
with open(fname) as fh:
    for line in fh:
        if not line.startswith('From: '): continue
        pieces = line.split()
        email = pieces[1]
        org = email.split('@')[1]

        cur.execute('SELECT count FROM Counts WHERE org = ?', (org,))
        row = cur.fetchone()
        if row is None:
            cur.execute('INSERT INTO Counts (org, count) VALUES (?, 1)', (org,))
        else:
            cur.execute('UPDATE Counts SET count = count + 1 WHERE org = ?', (org,))

conn.commit()

# Check result
sqlstr = 'SELECT org, count FROM Counts ORDER BY count DESC LIMIT 1'
for row in cur.execute(sqlstr):
    print(f'Top org: {row[0]} with count {row[1]}')

# Save file for download
conn.close()

# Create app.py file
app_code = '''
from flask import Flask, render_template, request, redirect, url_for
from datetime import datetime

app = Flask(__name__)

@app.route("/", methods=["GET"])
def home():
    return render_template("home.html")

@app.route("/select", methods=["POST"])
def select():
    event_type = request.form["event_type"]
    event_date = request.form["event_date"]
    return redirect(url_for("countdown", event_type=event_type, event_date=event_date))

@app.route("/countdown/<event_type>/<event_date>")
def countdown(event_type, event_date):
    target_date = datetime.strptime(event_date, "%Y-%m-%d").date()
    today = datetime.today().date()
    days_left = (target_date - today).days
    return render_template("countdown.html", event_type=event_type, days_left=days_left, event_date=event_date)
'''

with open("app.py", "w") as f:
    f.write(app_code)